N_MATCHES = 3

TEAMS = [
    "ADIA",
    "AI-liens",
    "Ai caramba",
    "Ale to Ty dzwonisz!",
    "Almost Magisters",
    "BatchNormies3d",
    "Blazing Code",
    "CUDA na kiju",
    "Capybara Intelligence Agency",
    "Crocozard",
    "Crunchy Byte",
    "Data Science | PolSl",
    "Foo Fighters",
    "Gen-Z4ikers",
    "Gradient Descendants",
    "KERAJ",
    "Kapibary",
    "Kyrie Eleison",
    "Latent Space Cowboys",
    "MIKOxTCS",
    "MoAI",
    "Nadbystrzaki",
    "Neurony bez żony",
    "Nie wiem",
    "OAIxMD Mates",
    "PAPuszki",
    "Pachołki",
    "PsAiCats",
    "Płomyk",
    "Rekurencyjne zapytanie DNS",
    "Skończona Liczba Studentów",
    "Somsiedzi",
    "Swiss Rolls",
    "Sztucznie inteligentni",
    "Słodziaki",
    "Teoria Wielkiego Modelu",
    "The Gradients",
    "The Systemizers",
    "Twoja odpowiedź",
    "Vlocznosc",
    "admin123",
    "pepega.ai",
    "Świta Znachora",
    "wiz.dev",
    "404 Brain Not Found",
    "test"
]

TEAMS_ABBREVIATIONS = [
    "ADIA",
    "AI-liens",
    "AiC",
    "ATTD",
    "AM",
    "BN3d",
    "BC",
    "CnK",
    "CIA",
    "Croco",
    "CB",
    "DSPS",
    "FF",
    "GZ",
    "GD",
    "KERAJ",
    "KAPI",
    "KE",
    "LSC",
    "MTCS",
    "MoAI",
    "NBS",
    "NBŻ",
    "NW",
    "OAIxMD",
    "PAP",
    "PACH",
    "PsC",
    "Płomyk",
    "RZDNS",
    "SLS",
    "Soms",
    "SR",
    "SI",
    "Słodziaki",
    "TWM",
    "TG",
    "TS",
    "TO",
    "Vlocznosc",
    "admin123",
    "pepega.ai",
    "ŚZ",
    "wiz.dev",
    "404BNF",
    "test"
]